<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
    <line>
      <![CDATA[<img src='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216335274.jpg' height='100' width='100'><a href='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216335274.jpg' target='_blank'>点击查看大图</a></img>]]>
    </line>
    <line>
      <![CDATA[<img src='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216340797.jpg' height='100' width='100'><a href='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216340797.jpg' target='_blank'>点击查看大图</a></img>]]>
    </line>
  </reporter-output>
  <suite name="webtest" duration-ms="14333" started-at="2021-10-14T20:58:46 CST" finished-at="2021-10-14T20:59:00 CST">
    <groups>
    </groups>
    <test name="Register" duration-ms="14314" started-at="2021-10-14T20:58:46 CST" finished-at="2021-10-14T20:59:00 CST">
      <class name="com.lemon.webauto.day05.RegisterCase">
        <test-method status="PASS" signature="init(java.lang.String)[pri:0, instance:com.lemon.webauto.day05.RegisterCase@282003e1]" name="init" is-config="true" duration-ms="1905" started-at="2021-10-14T20:58:46 CST" finished-at="2021-10-14T20:58:48 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="chioseHTTP()[pri:1, instance:com.lemon.webauto.day05.RegisterCase@282003e1]" name="chioseHTTP" duration-ms="368" started-at="2021-10-14T20:58:48 CST" finished-at="2021-10-14T20:58:48 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chioseHTTP -->
        <test-method status="PASS" signature="testNegativeCases(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.lemon.webauto.day05.RegisterCase@282003e1]" name="testNegativeCases" duration-ms="304" started-at="2021-10-14T20:58:49 CST" data-provider="datas_0" finished-at="2021-10-14T20:58:49 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[参数错误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeCases -->
        <test-method status="PASS" signature="testNegativeCases(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.lemon.webauto.day05.RegisterCase@282003e1]" name="testNegativeCases" duration-ms="215" started-at="2021-10-14T20:58:49 CST" data-provider="datas_0" finished-at="2021-10-14T20:58:49 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Willsm]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名密码错误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeCases -->
        <test-method status="FAIL" signature="testNegativeCases(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.lemon.webauto.day05.RegisterCase@282003e1]" name="testNegativeCases" duration-ms="5300" started-at="2021-10-14T20:58:49 CST" data-provider="datas_0" finished-at="2021-10-14T20:58:55 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Wills]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[参数错误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [参数错误] but found [用户名密码错误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [参数错误] but found [用户名密码错误]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.lemon.webauto.day05.RegisterCase.testNegativeCases(RegisterCase.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216335274.jpg' height='100' width='100'><a href='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216335274.jpg' target='_blank'>点击查看大图</a></img>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testNegativeCases -->
        <test-method status="FAIL" signature="testNegativeCases(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:com.lemon.webauto.day05.RegisterCase@282003e1]" name="testNegativeCases" duration-ms="5303" started-at="2021-10-14T20:58:55 CST" data-provider="datas_0" finished-at="2021-10-14T20:59:00 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Wills]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456789]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名密码错误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [用户名密码错误] but found [参数错误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [用户名密码错误] but found [参数错误]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.lemon.webauto.day05.RegisterCase.testNegativeCases(RegisterCase.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216340797.jpg' height='100' width='100'><a href='D:\project\webauto\target\surefire-reports\screenshot\Register\2021-10-14\1634216340797.jpg' target='_blank'>点击查看大图</a></img>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testNegativeCases -->
      </class> <!-- com.lemon.webauto.day05.RegisterCase -->
    </test> <!-- Register -->
    <test name="Register2" duration-ms="0" started-at="2021-10-14T20:59:00 CST" finished-at="2021-10-14T20:59:00 CST">
      <class name="com.lemon.webauto.day05.RegisterCase">
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.lemon.webauto.day05.RegisterCase@282003e1]" name="quitDriver" is-config="true" duration-ms="2659" started-at="2021-10-14T20:59:00 CST" finished-at="2021-10-14T20:59:03 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- com.lemon.webauto.day05.RegisterCase -->
    </test> <!-- Register2 -->
  </suite> <!-- webtest -->
</testng-results>
